#!/bin/bash


USERNAME=$USER                      #GET THE USER THROUGH USER COMMAND
DATETIME=$(date)                      #  OBTAIN THE DATE

#SYSTEM INFORMATION

HOSTNAME=$(hostname)                   #    GET THE HOSTNAME
OS=$(uname -s)                                   #    UNAMEW TO GAIN OS INFORMATION
UPTIME=$(uptime -p)                     #     USING UPTIME COMMAND


# HARDWARE INFORMATION


CPU=$(lshw -class processor | grep "product" | awk -F ': ' '{print $2}')            #LSHW COMMAND TO GET CPU MODEL NAME
RAM=$(free -h | grep "Mem:" | awk '{print $2}')                                     #RAM SIZE THROUGH FREE -H 
DISK=$(lshw -class disk | grep "product" | awk -F ': ' '{print $2}')                #   DISK NAME BY LSHW


# NETWORK INFORMATION

GATEWAY_IP=$(ip route | awk '/default via/ {print $3}')                    #  IP ROUTE USED FOFR GATEWAY IP
HOST_ADDRESS=$(hostname -I | awk '{print $1}')                             #  HOSTADDRESS BY HOSTNAME -I


IP_ADDRESS=$(hostname -I | awk '{print $1}')                                # GAIN THE IP ADDRESS


#SYSTEM STATUS

USER_LOGGED_IN=$(who)                                  #    WHO COMMAND TO GET LOGGON NAME
DISK_SPACE=$(df -h | grep "^/" | awk '{print $4 " (" $1 ")"}' | paste -sd, -)           #         GET THE DISK SIZE
UFW_RULES=$(sudo ufw status numbered)          #          SHOW UFW STATUS




#report output


cat<<EOF

SYSTEM_INFORMATION
===================
System Report generated by $USERNAME, $DATETIME

Hostname:$HOSTNAME
OS:$OS
UPTIME:$UPTIME


HARDWARE_INFORMATION
====================

CPU=$CPU
RAM=$RAM
DISK=$DISK



NETOWORK INFORMATION
====================

HOST_ADDRESS:$HOST_ADDRESS
GATEWAY_IP:$GATEWAY_IP

IP_ADDRESS=$IP_ADDRESS


SYSTEM STATUS
==============

USER_LOGGED_IN=$USER_LOGGED_IN
DISK_SPACE=$DISK_SPACE
UFW_RULES=$UFW_RULES



EOF
